# FROM node:16 AS Production
# FROM node:16
# FROM node:16.7.0-slim
FROM node:16.10.0

# ENV NODE_ENV=production

# WORKDIR /var/www/client
WORKDIR /client

# COPY package.json ./
# COPY package-lock.json ./

# COPY ./ ./

USER ubuntu

# RUN npm install
# RUN npm run build

# CMD ["sh", "-c", "npm run build"]
# CMD ["npm", "run", "build"]
# yarn build